const books = [
    {
        id: 1,
        title: "Book 1",
        author: "Author 1",
        category: "Fiction",
        course: "Computer Science",
        image: "@/assets/logo.png",
    },
    {
        id: 2,
        title: "Book 2",
        author: "Author 2",
        category: "Non-Fiction",
        course: "History",
        image: "book2.jpg",
    },
    {
        id: 3,
        title: "Book 3",
        author: "Author 3",
        category: "Mystery",
        course: "Mathematics",
        image: "book3.jpg",
    },
    {
        id: 4,
        title: "Book 4",
        author: "Author 4",
        category: "Fiction",
        course: "Biology",
        image: "book4.jpg",
    },
    {
        id: 5,
        title: "Book 5",
        author: "Author 5",
        category: "Non-Fiction",
        course: "Computer Science",
        image: "book5.jpg",
    },
    {
        id: 6,
        title: "Book 6",
        author: "Author 6",
        category: "Mystery",
        course: "History",
        image: "book6.jpg",
    },
    {
        id: 7,
        title: "Book 7",
        author: "Author 7",
        category: "Fiction",
        course: "Mathematics",
        image: "book7.jpg",
    },
    {
        id: 8,
        title: "Book 8",
        author: "Author 8",
        category: "Non-Fiction",
        course: "Biology",
        image: "book8.jpg",
    },
    {
        id: 9,
        title: "Book 9",
        author: "Author 9",
        category: "Mystery",
        course: "Computer Science",
        image: "book9.jpg",
    },
    {
        id: 10,
        title: "Book 10",
        author: "Author 10",
        category: "Fiction",
        course: "History",
        image: "book10.jpg",
    },
]
export default books